local M = {
	base46 = "jayden-chan/base46.nvim",
	blink_cmp = "Saghen/blink.cmp",
	devicons = "nvim-tree/nvim-web-devicons",
	fidget = "j-hui/fidget.nvim",
	fzf_lua = "ibhagwan/fzf-lua",
	gitlinker = "linrongbin16/gitlinker.nvim",
	gitsigns = "lewis6991/gitsigns.nvim",
	indent_blankline = "lukas-reineke/indent-blankline.nvim",
	lexima = "cohama/lexima.vim",
	lspconfig = "neovim/nvim-lspconfig",
	lspsaga = "nvimdev/lspsaga.nvim",
	lualine = "nvim-lualine/lualine.nvim",
	luasnip = "L3MON4D3/LuaSnip",
	neotree = "nvim-neo-tree/neo-tree.nvim",
	none_ls = "nvimtools/none-ls.nvim",
	none_ls_extras = "nvimtools/none-ls-extras.nvim",
	nui = "MunifTanjim/nui.nvim",
	plenary = "nvim-lua/plenary.nvim",
	tabular = "godlygeek/tabular",
	tmux_navigator = "christoomey/vim-tmux-navigator",
	todo_comments = "folke/todo-comments.nvim",
	treesitter = "nvim-treesitter/nvim-treesitter",
	treesitter_textobjects = "nvim-treesitter/nvim-treesitter-textobjects",
	trouble = "folke/trouble.nvim",
	ts_commentstring = "JoosepAlviste/nvim-ts-context-commentstring",
	vim_repeat = "tpope/vim-repeat",
	vim_surround = "tpope/vim-surround",
}

return M
