[time]
disabled = false
utc_time_offset = "local"
format = "[\\[ $time \\]]($style) "
time_format = "%-l:%M:%S"

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[\\$](bold green)"

[package]
disabled=true

[git_status]
disabled=false
