[time]
disabled = false
utc_time_offset = "-6"
format = "[\\[ $time \\]]($style) "
time_format = "%-l:%M:%S"

[character]
error_symbol = "[✗](bold red) "
success_symbol = "[\\$](bold green)"
use_symbol_for_status=true

[package]
disabled=true

[git_status]
disabled=false
