set nocompatible

filetype off

" Plugins

    set rtp+=$HOME/.vim/bundle/Vundle.vim
    call vundle#begin()

    Plugin 'VundleVim/Vundle.vim'
    Plugin 'scrooloose/nerdtree'
    Plugin 'MarcWeber/vim-addon-mw-utils'
    Plugin 'tomtom/tlib_vim'
    Plugin 'garbas/vim-snipmate'
    Plugin 'vim-airline/vim-airline'
    Plugin 'gcmt/taboo.vim'
    Plugin 'jiangmiao/auto-pairs'
    Plugin 'tiagofumo/vim-nerdtree-syntax-highlight'
    Plugin 'tpope/vim-commentary'
    Plugin 'tpope/vim-surround'
    Plugin 'godlygeek/tabular'
    Plugin 'junegunn/goyo.vim'
    Plugin 'pangloss/vim-javascript'
    Plugin 'mxw/vim-jsx'
    Plugin 'fatih/vim-go'
    Plugin 'buoto/gotests-vim'
    Plugin 'airblade/vim-gitgutter'
    Plugin 'Shougo/deoplete.nvim'
    Plugin 'zchee/deoplete-go'
    Plugin 'roxma/nvim-yarp'
    Plugin 'roxma/vim-hug-neovim-rpc'
    Plugin 'wellle/targets.vim'
    Plugin 'leafgarland/typescript-vim'
    Plugin 'morhetz/gruvbox'

    call vundle#end()
    filetype plugin indent on

" Behaviour

    " Theme
    syntax on

    " 256 colors
    set t_Co=256
    set t_ut=
    set termguicolors

    set background=dark
    let g:gruvbox_contrast_dark='hard'
    let g:gruvbox_sign_column='bg0'
    let g:gruvbox_italic=1
    let g:gruvbox_bold=1
    let g:gruvbox_underline=1
    colorscheme gruvbox

    " Tab settings
    set expandtab
    set shiftwidth=4
    set softtabstop=4
    set smarttab
    set smartindent

    " Use backspace
    set backspace=indent,eol,start

    " Search settings
    set gdefault           " Global by default
    set ignorecase         " Ignore case
    set smartcase          " Override ignorecase if search contains capitals
    set incsearch          " Search incrementally
    set nohls              " Don't highlight after Enter is pressed
    set inccommand=nosplit " Show find/replace as it is typed

    " Open new splits on the right
    set splitright

    " Nice line wraps
    set linebreak
    set breakindent

    " Fold settings
    set foldlevel=1000
    set foldmethod=indent

    " I mess up a lot
    set undolevels=9001

    " Cursor line
    set cursorline

    " No command bar
    set noshowmode

    " Hide ugly completion messages
    set shortmess+=c

    " Don't let the cursor reach the top/bottom 8 lines of text
    set scrolloff=8

    " Automatically update working dir
    set autochdir

    " Don't open preview windows
    set completeopt-=preview

    " Set .tex files to LaTeX syntax
    let g:tex_flavor = "latex"

    " Make LaTeX live preview smoother
    set updatetime=500

    " Enable mouse
    set mouse=a

    " Change cursor to bar and underscore for different modes
    let &t_SI = "\<Esc>[6 q"
    let &t_SR = "\<Esc>[4 q"
    let &t_EI = "\<Esc>[2 q"

" Binds

    " Leader
    let mapleader = "\<Space>"

    " Relative line number toggle
    set number relativenumber
    map <F9> <Esc>:set<Space>rnu!<CR>

    " Reload vimrc
    map <leader>ss :so $MYVIMRC<CR>

    " Map Ctrl-s to save because I am a compulsive saver
    nmap <c-s> :wa<CR>
    imap <c-s> <Esc>:wa<CR>

    " Spell check
    map <F6> :setlocal spell! spelllang=en_us<CR>
    set spellfile=$HOME/.vim/en.utf-8.add

    " ez semicolons (perhaps the greatest bind in this entire config)
    inoremap ;; <Esc>A;

    " Formatting (remove whitespace and reindent)
    noremap <leader>ww :%s/\s\+$//e<CR>
    noremap <leader>tt mtgg=G`tzz

    " Close quickfix
    noremap <c-q> :ccl<CR>

    " Remap cursor movement keys because I'm a scrub and don't use the default
    noremap h i
    noremap j h
    noremap k gj
    noremap i gk

    " Various other cursor control maps
    noremap L g$
    noremap J g^
    noremap I 12<c-u>
    noremap K 12<c-d>
    nnoremap <leader>c J

    " Change splits
    nnoremap <leader>j <C-w>h
    nnoremap <leader>k <C-w>j
    nnoremap <leader>i <C-w>k
    nnoremap <leader>l <C-w>l

    " Move the cursor more easily while in insert mode
    inoremap <c-j> <Left>
    inoremap <c-l> <Right>

    " Easily resize splits
    nnoremap <c-i> :resize -2<CR>
    nnoremap <c-k> :resize +2<CR>
    nnoremap <c-j> :vertical resize +5<CR>
    nnoremap <c-l> :vertical resize -5<CR>

    " Disable Ex mode
    map q: <nop>
    map Q <nop>

    " Used for centering text in the 'thicc' comments
    map <c-m> ^f*a<Space><Esc>f*h<Space><Esc>^

    " New line no insert mode
    map go o<Esc>

    " Copy Paste etc from system clipboard
    map <silent> <leader>p "+p
    map <silent> <leader>y "+y

    " Delete line without filling yank buffer
    nnoremap <silent> <leader>dd "_dd
    vnoremap <silent> <leader>dd "_dd

    " Prevent x and c from filling buffer
    noremap x "_x
    noremap c "_c
    noremap cc "_cc

    " Tab switching
    map <tab>j :tabprevious<CR>
    map <tab>l :tabnext<CR>

    " Fix 'I' behaviour in V-block
    vnoremap H I

" Plugin specific settings

    let NERDTreeMapOpenSplit='h'
    map <c-n> :NERDTreeToggle<CR>

    let g:snipMate = get(g:, 'snipMate', {})
    let g:snipMate = {}
    let g:snipMate.no_default_aliases = 1

    let g:airline_powerline_fonts = 1
    let g:airline_section_c = '%t'

    let g:NERDTreeFileExtensionHighlightFullName = 1
    let g:NERDTreeExactMatchHighlightFullName = 1
    let g:NERDTreePatternMatchHighlightFullName = 1
    let NERDTreeAutoDeleteBuffer = 1

    let g:deoplete#enable_at_startup = 1

    " Set git-gutter column to always on
    set signcolumn=yes
    let g:gitgutter_map_keys = 0

    let g:goyo_width = 120

    let g:go_doc_keywordprg_enabled = 0
    let g:go_highlight_methods=1
    let g:go_highlight_functions=1
    let g:go_highlight_function_calls = 1
    let g:go_highlight_extra_types = 1
    let g:go_highlight_types = 1
    let g:go_highlight_variable_declarations = 1
    let g:go_textobj_enabled = 0
    let g:go_list_type = "quickfix"

" Commands

    " Make leaving easier in case of typos
    command Q :q
    command Wq :wq
    command WQ :wq
    command Wqa :wqa
    command WQa :wqa
    command Qa :qa
    command QA :qa
    command Minify :%s/\s// | :%s/\n//

    " Mirror NERDTree when file is opened in new window
    autocmd BufWinEnter *.* NERDTreeMirror

    " Enable spell check for certain file types
    autocmd FileType gitcommit,text,markdown,tex setlocal spell

    " Set indentation to 2 spaces for certain files
    autocmd FileType javascript,typescript,html,css,json setlocal shiftwidth=2
    autocmd FileType javascript,typescript,html,css,json setlocal softtabstop=2

    " Set indentation to hard tabs for some files
    autocmd FileType snippets,go setlocal tabstop=4
    autocmd FileType snippets,go setlocal shiftwidth=4
    autocmd FileType c,asm       setlocal shiftwidth=8
    autocmd FileType go          setlocal noexpandtab

    " Easily open corresponding source file (C/C++)
    autocmd FileType c,cpp nmap <silent> <leader>vv :vs ../src/%<.*<CR>

" Abbreviations

    iab retrun   return
    iab retnru   return
    iab erturn   return
    iab ertnru   return
    iab thsi     this
    iab fcuntoin function
    iab fucntion function
    iab costn    const
    iab conts    const
    iab THe      The
    iab !+       !=
