#!/bin/dash
# vim: ft=sh

DOTS="$HOME"/.config/dotfiles
HOSTNAME=$(hostname)

##########################################################
#                      bspc config                       #
##########################################################

bspc config window_gap                 10
bspc config top_padding                0
bspc config right_padding              14
bspc config bottom_padding             14
bspc config left_padding               14

bspc config border_width               0
bspc config focused_border_color       '#ffffff'
bspc config normal_border_color        '#30302f'
bspc config active_border_color        '#30302f'
bspc config presel_feedback_color      '#717e88'

bspc config borderless_monocle         false
bspc config gapless_monocle            false
bspc config single_monocle             false

bspc config focus_follows_pointer      true
bspc config pointer_follows_monitor    false

bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors false

bspc config pointer_modifier           mod1
bspc config pointer_action2            resize_corner
bspc config pointer_action1            move

bspc rule -a Nitrogen                 state=floating
bspc rule -a Org.gnome.Nautilus       state=floating
bspc rule -a pw-display               state=floating
bspc rule -a Eog                      state=floating
bspc rule -a Blueman-manager          state=floating
bspc rule -a Sxiv                     state=floating
bspc rule -a Zathura                  state=tiled
bspc rule -a Gedit                    state=floating
bspc rule -a File-roller              state=floating
bspc rule -a '*:*:xyz.jaydenchan.cal' state=floating
bspc rule -a mpv                      state=floating
bspc rule -a origin.exe               state=floating

if [ "$HOSTNAME" = "grace" ]; then
    bspc rule -a discord desktop='DVI-D-0:^1'
fi

##########################################################
#                        Startup                         #
##########################################################

# If sxhkd is already running it probably means we're restarting bspwm.
# These items only need to be run on login, so don't run them again
pgrep -x sxhkd > /dev/null || nitrogen --restore &

if [ "$HOSTNAME" = "grace" ]; then
    pgrep -x Discord > /dev/null || discord \
        --ignore-gpu-blocklist \
        --disable-features=UseOzonePlatform \
        --enable-features=VaapiVideoDecoder \
        --use-gl=desktop \
        --enable-gpu-rasterization \
        --enable-zero-copy > /tmp/discord-stdout.log 2>&1 &

    sh "$DOTS"/scripts/eq.sh --mic &
else
    (killall nm-applet; sleep 0.3; nm-applet) &
    (killall pasystray; sleep 0.3; pasystray) &
fi

if [ "$HOSTNAME" = "swift" ]; then
    xmodmap -e "clear lock" &
    xmodmap -e "keysym Caps_Lock = Escape" &
fi

sh "$DOTS"/scripts/inputs.sh &
sh "$DOTS"/scripts/polybar.sh &
sh "$DOTS"/scripts/eq.sh &

for monitor in $(bspc query -M); do
    bspc monitor "$monitor" -d 1 2 3 4 5 6 7 8 9
done

pgrep -x sxhkd > /dev/null || sxhkd -c "$DOTS"/bspwm/sxhkdrc &
pgrep -x dunst > /dev/null || dunst -config "$DOTS"/misc/dunstrc &
pgrep -x picom > /dev/null || picom --config "$DOTS"/misc/picom.conf &

# remove the old xsession-errors file
rm -f "$HOME/.xsession-errors.old"
