{ pkgs, inputs, ... }:

{
  environment.systemPackages = with pkgs; [
    age
    age-plugin-yubikey
    alsa-utils
    anki
    awesome
    bash
    bat
    bc
    carla
    czkawka-full
    dig
    discord
    eza
    fastfetch
    fd
    feishin
    ffmpeg-full
    ffmpegthumbnailer
    file
    file-roller
    firefox-devedition
    fontconfig
    fzf
    (gimp-with-plugins.overrideAttrs ({ plugins = [ gimpPlugins.resynthesizer ]; }))
    go
    gopls
    gparted
    htop
    imagemagick
    jq
    killall
    libnotify
    lsp-plugins
    maim
    mediainfo
    mousepad
    mullvad-browser
    neovim
    nil
    nitrogen
    nixfmt
    nodejs_26
    nsxiv
    oxfmt
    pandoc
    passage
    pavucontrol
    picom
    qview
    redshift
    ripgrep
    rofi
    rsync
    spotify
    stylua
    taplo
    tokei
    trash-cli
    ungoogled-chromium
    usbutils
    watchexec
    wireguard-tools
    x42-plugins
    yq-go
    yt-dlp
    yubikey-manager
    zbar
    zsh-syntax-highlighting

    bash-language-server
    lua-language-server
    yaml-language-server

    # needed for nvim tree-sitter
    gcc
    tree-sitter

    xclip
    xcolor
    xdotool
    xev
    xinput
    xmodmap
    xprop
    xrdb
    xset

    inputs.agenix.packages.${stdenv.hostPlatform.system}.default
    inputs.notifications-dbus-mon.packages."${stdenv.hostPlatform.system}".default
    inputs.spotify-dbus-mon.packages."${stdenv.hostPlatform.system}".default
    inputs.git-check.packages."${stdenv.hostPlatform.system}".default
    inputs.mdv.packages."${stdenv.hostPlatform.system}".default
    inputs.mediaman.packages."${stdenv.hostPlatform.system}".default
    inputs.prodge.packages."${stdenv.hostPlatform.system}".default
    inputs.weblogs.packages."${stdenv.hostPlatform.system}".default
  ];
}
