{
  pkgs,
  unstable,
  inputs,
  ...
}:

{
  environment.systemPackages = with pkgs; [
    age
    age-plugin-yubikey
    alsa-utils
    awesome
    bash
    bat
    bc
    bun
    carla
    chromium
    czkawka-full
    dig
    eza
    fastfetch
    fd
    ffmpeg-full
    ffmpegthumbnailer
    file
    fontconfig
    fzf
    gcc
    gimp
    gnumake
    go
    imagemagick
    jalv
    joplin-desktop
    jq
    killall
    libnotify
    lsp-plugins
    lua-language-server
    maim
    mediainfo
    mullvad-browser
    nitrogen
    nixfmt-rfc-style
    nsxiv
    obs-studio
    onefetch
    passage
    pavucontrol
    picom
    pkg-config
    prettierd
    qview
    redshift
    ripgrep
    rofi
    rsync
    shellcheck
    socat
    stylua
    taplo
    tokei
    trash-cli
    trufflehog
    typst
    usbutils
    vesktop
    wget
    wireguard-tools
    x42-plugins
    xclip
    xcolor
    xdotool
    yaml-language-server
    yubikey-manager
    zbar
    zenity
    zoxide
    zsh-syntax-highlighting

    nodePackages.typescript-language-server

    python312Packages.grip

    xfce.mousepad

    xorg.xev
    xorg.xinput
    xorg.xmodmap
    xorg.xprop
    xorg.xrdb
    xorg.xset

    unstable.bruno
    unstable.devenv
    unstable.feishin
    unstable.firefox-devedition
    unstable.ghostty
    unstable.neovim
    unstable.nil
    unstable.picocrypt
    unstable.picocrypt-cli
    unstable.spotify
    unstable.yt-dlp

    inputs.agenix.packages.${system}.default
    inputs.notifications-dbus-mon.packages."${system}".default
    inputs.spotify-dbus-mon.packages."${system}".default
  ];
}
