ln -fs ~/Documents/Git/dotfiles/compton/compton.conf ~/.config/compton.conf
ln -fs ~/Documents/Git/dotfiles/dunst/dunstrc        ~/.config/dunst/dunstrc
ln -fs ~/Documents/Git/dotfiles/i3/config            ~/.config/i3/config
ln -fs ~/Documents/Git/dotfiles/polybar/config       ~/.config/polybar/config
ln -fs ~/Documents/Git/dotfiles/termite/config       ~/.config/termite/config
ln -fs ~/Documents/Git/dotfiles/tmux/.tmux.conf      ~/.tmux.conf
ln -fs ~/Documents/Git/dotfiles/vim/vimrc            ~/.vimrc
ln -fs ~/Documents/Git/dotfiles/zsh/zshrc            ~/.zshrc
ln -fs ~/Documents/Git/dotfiles/zsh/zlogout          ~/.zlogout
ln -fs ~/Documents/Git/dotfiles/vim/en.utf-8.add     ~/.vim/en.utf-8.add
ln -fs ~/Documents/Git/dotfiles/snippets             ~/.vim/snippets
