rm -r ~/.config/compton.conf 2>/dev/null
rm -r ~/.config/dunst/dunstrc 2>/dev/null
rm -r ~/.config/i3/config 2>/dev/null
rm -r ~/.config/polybar/config 2>/dev/null
rm -r ~/.config/termite/config 2>/dev/null
rm -r ~/.tmux.conf 2>/dev/null
rm -r ~/.vimrc 2>/dev/null
rm -r ~/.zshrc 2>/dev/null
rm -r ~/.zlogout 2>/dev/null
rm -r ~/.vim/en.utf-8.add 2>/dev/null
rm -r ~/.vim/snippets 2>/dev/null

ln -s ~/Documents/Git/dotfiles/compton/compton.conf ~/.config/compton.conf
ln -s ~/Documents/Git/dotfiles/dunst/dunstrc        ~/.config/dunst/dunstrc
ln -s ~/Documents/Git/dotfiles/i3/config            ~/.config/i3/config
ln -s ~/Documents/Git/dotfiles/polybar/config       ~/.config/polybar/config
ln -s ~/Documents/Git/dotfiles/termite/config       ~/.config/termite/config
ln -s ~/Documents/Git/dotfiles/tmux/.tmux.conf      ~/.tmux.conf
ln -s ~/Documents/Git/dotfiles/vim/vimrc            ~/.vimrc
ln -s ~/Documents/Git/dotfiles/zsh/zshrc            ~/.zshrc
ln -s ~/Documents/Git/dotfiles/zsh/zlogout          ~/.zlogout
ln -s ~/Documents/Git/dotfiles/vim/en.utf-8.add     ~/.vim/en.utf-8.add
ln -s ~/Documents/Git/dotfiles/snippets             ~/.vim/snippets
