# vim: ft=sh

hostname="$(hostname)"

# XDG Base Directory
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_DESKTOP_HOME="$HOME"/.local/desktop
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_CACHE_HOME="$HOME"/.cache
export XDG_STATE_HOME="$HOME"/.local/state

# Clean up home directory
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
export GRIPHOME="$XDG_CONFIG_HOME"/grip
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export HISTFILE="$XDG_STATE_HOME"/zsh/history
export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEauthority
export IPYTHONDIR="$XDG_CONFIG_HOME"/jupyter
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME"/jupyter
export LESS="-RX"
export LESSHISTFILE="-"
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export SQLITE_HISTORY=$XDG_DATA_HOME/sqlite_history
export SSB_HOME="$XDG_DATA_HOME"/zoom
export TEXMFVAR="$XDG_CACHE_HOME"/texlive/texmf-var
export WGETRC="$HOME"/.config/wget/wgetrc
export ZDOTDIR="$HOME"/.config/zsh
export KUBECACHEDIR="$XDG_CACHE_HOME"/kube
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export _Z_DATA="$XDG_DATA_HOME"/z
export VOLTA_HOME="$HOME/.local/share/volta"

# Private vars (mostly tokens)
[ -e "$HOME/.config/ENV" ] && source $HOME/.config/ENV

# Config
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox-developer-edition"
export COLORTERM="truecolor"
export DOT="$HOME/.config/dotfiles"

export DO_NOT_TRACK=1
# Opt out of .NET telemetry (yikes...)
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export GATSBY_TELEMETRY_DISABLED=1
export DENO_NO_UPDATE_CHECK=1
export GOPROXY=direct

# Export Go path
export GOPATH="$XDG_DATA_HOME"/go
export PATH=$GOPATH/bin:$PATH

# Add cargo binaries
export PATH="$XDG_DATA_HOME/cargo/bin:$PATH"

# Add other binaries
export PATH="$HOME/.local/bin:$PATH"

# Volta binaries
export PATH="$VOLTA_HOME/bin:$PATH"

# work laptop stuff
if [ "$hostname" = "Yellow-Lion.local" ]; then
    export PATH="$PATH:/opt/homebrew/bin"
fi

# Ensure GPG sign prompt shows on correct screen
export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye >/dev/null

if [ "$hostname" = "swift" ] || [ "$hostname" = "grace" ]; then
    if [ -n "$DESKTOP_SESSION" ];then
        eval $(gnome-keyring-daemon --start 2>/dev/null)
        export SSH_AUTH_SOCK
    fi

    xrdb -load ~/.config/dotfiles/misc/Xresources
fi

# NPM global
export PATH=~/.local/share/npm/bin:$PATH

unset MANPATH
export MANPATH="$NPM_PATH/share/man:$(manpath)"

# Android studio stuff for React Native
export ANDROID_HOME=$HOME/Dev/Android
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
